In [ ]:
1.What is NumPy, and why is it widely used in Python ?

 numpy provide powerful array object and tools for working with these array.
 Also numpy is pythone library which generally provide functione realated to mathmaticle operation ,
 It includes a suite of mathematical functions for operations like linear algebra, Fourier transforms, and statistical analysis.


IT is mainly used for
- Speed: NumPy arrays are stored in contiguous memory blocks, enabling fast access and manipulation. This makes them up to 50x faster than Python lists.
- Vectorization: You can apply operations to entire arrays without writing explicit loops. This is both cleaner and faster.
- Broadcasting: NumPy can perform operations on arrays of different shapes by automatically expanding dimensions—no need to manually reshape data.
- Integration: It’s the foundation for libraries like Pandas, SciPy, TensorFlow, and scikit-learn. Most scientific Python packages convert inputs to NumPy arrays before processing.
- Low-level optimization: Core operations are written in C/C++, giving it the performance edge while keeping Python’s readability.
1.

 2.How does broadcasting work in NumPy?                                          
  suppose there are two arrays with diff shape one is one_dimension array and other is two dimension when we perform artematic operation in between these array . the array with small shape automatically expanded to match the shape of larger array .

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
b = np.array([10, 20, 30])           # shape (3,)

print(a + b)


>> Output: [[11 22 33]
          [14 25 36]]

3.What is a Pandas DataFrame?
 pandas dataframe is used to present data in tabular form (i.e :  In raws and column), it maninly arrange comma seprated value in tabular form .

 example


```
# This is formatted as code

 import pandas as pd
 data = {'Name' : ['a', 'b' , 'c', 'd'],
  'age' : [20, 21, 22, 23] ,
  'marks' : [34 , 35, 36 , 37] }

  a = pd.DataFrame(data)



 4.Explain the use of the groupby() method in Pandas ?
  
 group() method is used to split data into groups , It split data on the bases of function like mean(), sum() , max() , count().

 example  

```
# This is formatted as code

import pandas as pd
d = { 'name' : ['a','b','a','d','b','a','d'],
     'marks' : [10,20,30,40,50,60,70] }
a = pd.DataFrame(d)
a.groupby('name')['marks'].sum()

In [ ]:
import pandas as pd
d = { 'name' : ['a','b','a','d','b','a','d'],
     'marks' : [10,20,30,40,50,60,70] }
a = pd.DataFrame(d)
a.groupby('name')['marks'].sum()

name
a    100
b     70
d    110
Name: marks, dtype: int64

5.Why is Seaborn preferred for statistical visualizations?                       
 Seaborn is preferred for statistical visualizations because it turns raw data into insightful, elegant graphics with minimal code and maximum clarity. It’s not just a wrapper around Matplotlib—it’s a high-level toolkit built for data exploration, pattern recognition, and storytelling.


6.What are the differences between NumPy arrays and Python lists?

numpy array : numpy array is  multi_dimesional , numpy array are homogenius(i.e : all element in array is of same type) , numpy array provide fast numaric operation , it consist rich set of mathamaticle operation

list : list is one dimensional , list is hetrogenuis , numeric opration are slow , used for general purpose

7. What is a heatmap, and when should it be used?

- It’s a 2D graphical representation where each cell’s color reflects a numerical value.
- Commonly used to highlight patterns, trends, and anomalies in large datasets.
- The intensity of color helps viewers quickly grasp areas of interest or concern.


Use heatmaps when you want to:
- Spot patterns at a glance: Perfect for correlation matrices, sensor grids, or performance metrics.
- Compare values across categories: Like student scores across subjects or traffic across time slots.
- Identify outliers or clusters: Useful in cybersecurity, IoT, and automation logs.
- Visualize density or frequency: For example, website click behavior or retail footfall analysis


8.What does the term “vectorized operation” mean in NumPy?

In NumPy, a vectorized operation means performing computations on entire arrays without using explicit loops. It’s like telling NumPy: “Apply this operation to everything—all at once.” Behind the scenes, NumPy uses highly optimized C code to make this blazing fast.




9. How does Matplotlib differ from Plotly?

Matplotlib and Plotly are both powerful Python libraries for data visualization—but they serve different purposes and shine in different contexts. Think of Matplotlib as the classic artist and Plotly as the modern designer.

- Type: Primarily for static plots (though it supports basic interactivity).
- Customization: Extremely flexible—you can control every pixel, but it often requires more code.
- Use Case: Ideal for academic papers, print-ready figures, and precise control over layout.
- Integration: Foundation for libraries like Seaborn and Pandas plotting.
- Output: Generates images (PNG, PDF, etc.)—great for reports and publications.


10. What is the significance of hierarchical indexing in Pandas?

Hierarchical indexing (or MultiIndexing) in pandas is a powerful feature that lets you work with higher-dimensional data in a two-dimensional DataFrame or Series. Here's why it's significant—especially for someone like you, Kartikesh, who’s building teaching modules and cheat sheets for learners in automation and data science:


11.What is the role of Seaborn’s pairplot() function?

- It creates scatter plots for every pair of numeric columns.
- On the diagonal, it shows the distribution of each variable (like histograms or KDE plots).
- You can use the hue parameter to color-code points by category—great for spotting patterns across classes.


12. What is the purpose of the describe() function in Pandas?

 The describe() function in pandas is like a quick health check for your dataset. It gives you a summary of the most important statistics so you can understand your data better—without wr-  
 - count:How many non-missing values there are
- mean: The average value
- std: Standard deviation (how spread out the values are)
- min and max: The smallest and largest values
- 25%, 50%, 75%: Percentiles (helps you understand the distribution)
iting a bunch of code.

uses
- Helps you spot missing data, outliers, or weird distributions
- Gives a quick overview before plotting or modeling
- Useful for data cleaning, feature engineering, and interview prep




13. Why is handling missing data important in Pandas?

andling missing data in pandas is crucial because bad or incomplete data leads to bad decisions. Whether you're analyzing sensor logs, building predictive models, or preparing teaching materials, ignoring missing values can seriously mess things up

- Accuracy: Missing values can distort averages, correlations, and trends. For example, calculating the mean temperature from a smart building dataset without handling NaN values will give incorrect results.
- Model Performance: Machine learning algorithms don’t like NaNs. They might crash or give poor predictions unless you clean the data first.
- Data Integrity: Unhandled gaps can lead to misleading visualizations or summaries. Imagine showing a bar chart where one category is missing just because the data wasn’t filled properly.
- Better Insights: Filling missing values with smart defaults (like mean, median, or interpolation) helps preserve patterns and relationships in the data.


14.What are the benefits of using Plotly for data visualization?

What are the benefits of using Plotly for data visualization

1. Interactive Charts
- Zoom, pan, hover, and click to explore data dynamically.
- Great for dashboards, presentations, or teaching—learners can engage with the data directly.
2. Minimal Code, Maximum Output
- With plotly.express, you can create complex visuals in just one line of Python:
3. Beautiful and Customizable
- Clean, modern visuals with full control over layout, colors, annotations, and more.
- You can tweak every detail to match your branding or teaching style.
4. Supports Big Data and Advanced Analytics
- Handles large datasets efficiently.
- Integrates well with machine learning, forecasting, and NLP workflows.
5. Cross-Language Compatibility
- Works with Python, R, Julia, and JavaScript—ideal for multilingual teams or cross-platform projects.




15.How does NumPy handle multidimensional arrays?

NumPy handles multidimensional arrays using a powerful object called the ndarray, which stands for N-dimensional array. This is the backbone of NumPy and allows you to work with data in 1D, 2D, 3D, or even higher dimensions.


- Shape: Every array has a .shape attribute that tells you the size of each dimension.
Example: A 2D array with 3 rows and 4 columns has shape (3, 4).
- Indexing and Slicing: You can access elements using multiple indices.
Example: arr[1, 2] gets the element in row 1, column 2 of a 2D array.
- Reshaping: You can change the dimensions using .reshape().
Example: Convert a 1D array of 12 elements into a 3D array of shape (2, 2, 3).


16.What is the role of Bokeh in data visualization?

Bokeh plays a powerful role in data visualization by helping you create interactive, web-ready plots using Python—without needing to write JavaScript. It’s especially useful when you want your visuals to be dynamic, shareable, and scalable.


17.Explain the difference between apply() and map() in Pandas?


map() is designed specifically for Series objects. It works element by element, applying a function to each individual value. Think of it like editing each word in a sentence—simple, direct, and great for tasks like formatting strings, replacing values, or scaling numbers. For example, if you have a column of temperatures in Celsius and want to convert them to Fahrenheit, map() is perfect.
On the other hand, apply() is more flexible. It works on both Series and DataFrames. When used on a Series, it behaves similarly to map(). But when used on a DataFrame, it can apply a function across rows or columns, depending on the axis you choose. This makes it ideal for more complex operations—like computing the maximum value across each row, or applying a custom function that combines multiple columns.
So in short: use map() for simple, element-wise transformations on a single column, and reach for apply() when you need more control or want to work across multiple columns or rows.



18. What are some advanced features of NumPy?

1. Broadcasting
This lets you perform operations on arrays of different shapes without writing loops. For example, adding a 1D array to each row of a 2D array—NumPy automatically stretches the smaller array to match the shape.

2. Vectorized Operations
NumPy replaces slow Python loops with fast, compiled C operations under the hood. You can apply mathematical functions directly to arrays—like np.sin(arr) or arr ** 2—and it runs lightning-fast.

3.Linear Algebra
NumPy includes a full suite of linear algebra tools: matrix multiplication (@ or np.dot()), eigenvalues, determinants, inverses, and more. Perfect for signal processing, control systems, or smart building simulations.

5.. Random Number Generation
The np.random module lets you simulate data, generate noise, or run Monte Carlo experiments. You can draw from normal, uniform, binomial distributions and more.

6. Memory Mapping and File I/O
For massive datasets, NumPy supports memory-mapped files (np.memmap) so you can work with data that doesn’t fit in RAM. It also supports saving/loading arrays in binary (.npy) or text formats.




19. How does Pandas simplify time series analysis?

Pandas makes time series analysis surprisingly smooth by giving you tools that feel natural and intuitive—especially when working with dates, trends, and patterns over time.
Here's how it simplifies the process:
1. DateTime Indexing
You can set a column of timestamps as the index, which lets you filter, slice, and resample data based on time. For example, you can easily grab all rows from January 2025 with just:
df['2025-01']


2. Resampling
Need to convert daily data to monthly averages or hourly logs to 10-minute intervals? Pandas makes this easy with .resample():
df.resample('M').mean()  # Monthly average


3. Rolling Windows
You can calculate moving averages or rolling sums to smooth out noisy data:
df['temp'].rolling(window=7).mean()  # 7-day moving average


4. Time Shifting
Want to compare today’s data with yesterday’s? Use .shift() to move data forward or backward in time:
df['temp_diff'] = df['temp'] - df['temp'].shift(1)


5. Frequency Conversion
Pandas lets you define and change the frequency of your time series—like converting minute-level data to hourly or daily summaries.
6. Built-in Date Handling
It integrates seamlessly with Python’s datetime module, so you can parse, format, and manipulate dates without extra libraries.
7. Missing Data Handling
Time series often have gaps. Pandas can fill missing timestamps and interpolate values to keep your analysis clean and continuous.



20.What is the role of a pivot table in Pandas?

A pivot table in pandas plays the role of a data summarizer. It helps you reorganize, group, and aggregate your data in a way that makes patterns easier to spot—especially when you're dealing with large or messy datasets.

- Group data by region or date
- Calculate totals, averages, or counts
- Rearrange the layout so rows become columns and vice versa
This turns raw data into a clear, structured summary—like a mini report.



21.Why is NumPy’s array slicing faster than Python’s list slicing?

NumPy’s array slicing is faster than Python’s list slicing because it’s built for speed, memory efficiency, and numerical precision—all under the hood.
Here’s why it outperforms regular Python lists:

 1. Contiguous Memory Layout
NumPy arrays store data in a single, continuous block of memory. This means slicing doesn’t involve copying data—it just creates a view into the original array. Python lists, on the other hand, are made of scattered references to objects in memory, so slicing them involves creating a new list and copying each element.

 2. Fixed Data Types
NumPy arrays are homogeneous—every element is of the same type (like int32 or float64). This allows NumPy to skip type-checking during operations. Python lists are heterogeneous, so Python has to check each element’s type during slicing or arithmetic, which slows things down.

 3. Optimized C Backend
NumPy is written in C and uses highly optimized libraries like BLAS and LAPACK. When you slice or manipulate arrays, you’re tapping into compiled code that runs much fast


22. What are some common use cases for Seaborn?

Seaborn is a go-to library when you want to create statistical visualizations that are both beautiful and insightful—without writing a ton of code. It’s built on top of Matplotlib and works seamlessly with pandas, making it perfect for data exploration, teaching, and storytelling.
Here are some of the most common use cases:

 1. Visualizing Relationships Between Variables
Use scatter plots, line plots, and regression plots to explore how two or more variables interact. For example, you can show how temperature and humidity vary across sensor types using sns.scatterplot() or sns.lmplot().

 2. Distribution Analysis
Seaborn makes it easy to understand how data is spread out using histograms, KDE plots, and ECDF plots. These are great for spotting skewness, outliers, or multimodal distributions.




# ***practicle***

In [9]:
# 1. How do you create a 2D NumPy array and calculate the sum of each row?

import numpy as np
a = np.array([[1,2,3,4] , [5,6,7,8] , [9,10,11,12]])
a.sum(axis = 1)

array([10, 26, 42])

In [13]:
# 2.Write a Pandas script to find the mean of a specific column in a DataFrame?

import pandas as pd
data = { 'Age': [23,20,23,25,26,27,28],
        'marks': [45,67,89,89,70,34,35]}
a = pd.DataFrame(data)
mean = a['Age'].mean()
print("avg age is", mean)

avg age is 24.571428571428573


In [ ]:
# 3. Create a scatter plot using Matplotlib
import matplotlib.pyplot as plt
import numpy as np


x = np.array([10, 20, 30, 40, 50])
y = np.array([15, 25, 35, 45, 55])


plt.scatter(x, y, color='blue', marker='o')

plt.xlabel('X-axis values')
plt.ylabel('Y-axis values')
plt.title('Basic Scatter Plot')


plt.show()

In [ ]:
#4. How do you calculate the correlation matrix using Seaborn and visualize it with a heatmap?

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.DataFrame({
    'temperature': [22, 24, 21, 25, 23],
    'humidity': [55, 60, 58, 62, 59],
    'pressure': [1012, 1010, 1013, 1009, 1011]
})


corr_matrix = df.corr()


sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')


plt.title("Correlation Matrix Heatmap")
plt.show()

In [ ]:
#5. Generate a bar plot using Plotly

import plotly.express as px
import pandas as pd

data = pd.DataFrame({
    'Device': ['Sensor A', 'Sensor B', 'Sensor C', 'Sensor D'],
    'Readings': [120, 90, 150, 80]
})

fig = px.bar(data, x='Device', y='Readings', title='Sensor Readings Overview')
fig.show()

In [19]:
#6. Create a DataFrame and add a new column based on an existing column

import pandas as pd
data = { 'phy': [36,46,47,48,49,50],
        'math': [56,77,78,76,85,55],
         'chem': [56,56,67,45,76,88]}
a = pd.DataFrame(data)
a['totalmarks'] = a['phy'] +a['math']+ a['chem']
a

phy  math  chem  totalmarks
0   36    56    56         148
1   46    77    56         179
2   47    78    67         192
3   48    76    45         169
4   49    85    76         210
5   50    55    88         193

In [20]:
#7.Write a program to perform element-wise multiplication of two NumPy arrays

import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([[2,3,5,6],[7,4,2,6],[1,5,3,8]])
print(a*b)

[[ 2  6 15 24]
 [35 24 14 48]
 [ 9 50 33 96]]


In [ ]:
#8.Create a line plot with multiple lines using Matplotlib

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y1 = [10, 20, 25, 30, 40]
y2 = [5, 15, 20, 25, 35]
y3 = [2, 10, 15, 22, 28]

plt.plot(x, y1, label='Sensor A', marker='o')
plt.plot(x, y2, label='Sensor B', marker='s')
plt.plot(x, y3, label='Sensor C', marker='^')

plt.xlabel('Time')
plt.ylabel('Readings')
plt.title('Sensor Readings Over Time')
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
#9.Generate a Pandas DataFrame and filter rows where a column value is greater than a threshold
import pandas as pd

data = {
    'Device': ['Sensor A', 'Sensor B', 'Sensor C', 'Sensor D'],
    'Temperature': [22, 28, 19, 31]
}

df = pd.DataFrame(data)

filtered_df = df[df['Temperature'] > 25]

print(filtered_df)

In [ ]:
#10. Create a histogram using Seaborn to visualize a distribution
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

data = np.random.normal(loc=50, scale=10, size=1000)

sns.histplot(data, bins=30, kde=True, color='skyblue')

plt.title("Distribution of Sensor Readings")
plt.xlabel("Reading Value")
plt.ylabel("Frequency")
plt.show()

In [ ]:
#11. Perform matrix multiplication using NumPy
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)

print("Matrix multiplication result:\n", result)

In [26]:
#12. Use Pandas to load a CSV file and display its first 5 rows
import pandas as pd

df = pd.read_csv('your_file.csv')
print(df.head())

TypeError: 'DataFrame' object is not callable

In [ ]:
#13. Create a 3D scatter plot using Plotly
import plotly.express as px
import pandas as pd

df = pd.DataFrame({
    'x': [10, 20, 30, 40, 50],
    'y': [15, 25, 35, 45, 55],
    'z': [5, 10, 15, 20, 25],
    'label': ['A', 'B', 'C', 'D', 'E']
})

fig = px.scatter_3d(df, x='x', y='y', z='z', color='label', title='3D Scatter Plot Example')
fig.show()